version: '3.7'

services:
  web:
    image: "${WEB_IMAGE}"
    command: > 
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate --no-input &&
             python manage.py collectstatic --no-input
             gunicorn web_app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - django_static_volume:/usr/src/app/backend/backend_static
      - django_media_volume:/usr/src/app/backend/backend_media
    ports:
      - 8000:8000
    env_file: .env
    restart: "on-failure"
  react-nginx:
    image: "${REACT_NGINX_IMAGE}"
    volumes:
      - django_static_volume:/usr/src/app/backend/backend_static
      - django_media_volume:/usr/src/app/backend/backend_media
      - react_static_volume:/usr/src/app/frontend/build/static
    ports:
      - 80:80
    depends_on:
      - web
    restart: "on-failure"

volumes:
  django_static_volume:
  django_media_volume:
  react_static_volume: